### ISSUE TITLE
Change Foldernames to Lowercase

### ISSUE THREAD

**Issue by DSchalla** [flatlinee/flatHUD-#4]
Hello flatlinee,

Thanks first of all for creating the HUD! Linux (and maybe Mac?) Users won't
be able to use the HUD unless they rename the folder from "flathudRED" to "flathudred",
same for blue ofc. Would there be any disadvantage of making them lowercase by default?

That way they would automatically for everyone, just a thought.

Best Regards,
Daniel

**Comment by flatlinee** [comment]
Done.  Caps were just a stylistic option.

**Comment by DSchalla** [comment]
Thank you!
